/* Реальные названия авто в автосалонах */
const RealCarNames = {
/* Добавляете сюда свои авто, по примеру: */
/* "название_veh": "Реальное название которое будет показано" */

// premium
"Dukes": "Dukes",
"Sultan": "Sultan",
"SultanRS": "SultanRS",
"Kuruma": "Kuruma",
"Fugitive": "Fugitive",
"Tailgater": "Tailgater",
"Sentinel": "Sentinel",
"F620": "F620",
"Schwarzer": "Schwarzer",
"Exemplar": "Exemplar",
"Felon": "Felon",
"Schafter2": "Schafter2",
"Jackal": "Jackal",
"Oracle2": "Oracle2",
"Surano": "Surano",
"Zion": "Zion",
"Dominator": "Dominator",
"FQ2": "FQ2",
"Gresley": "Gresley",
"Serrano": "Serrano",
"Dubsta": "Dubsta",
"Rocoto": "Rocoto",
"Cavalcade2": "Cavalcade2",
"XLS": "XLS",
"Baller2": "Baller2",
"Elegy": "Elegy",
"Banshee": "Banshee",
"Massacro2": "Massacro2",
"GP1": "GP1",
"bc": "Pagani Huayra",
"jesko2020": "Koenigsegg Jesko 2020",
"bmwi7": "BMW i7",
"evcs850": "Brabus 850",
"mbc63": "Mercedes AMG C63",
"opeladam": "Opel Adam",
"pursport": "Bugatti Supersport",
"sf90": "Ferrari Stradale SF90",
"16challenger": "Dodge Challenger",
"17m760i": "BMW 760i",
"18performante": "Lamborghini Performante",
"63g4x4": "Mercedes G63 4x4",
"190e": "Mercedes 190e",
"300sl": "Mercedes 300 SL",
"488pista": "Ferrari 488 Pista",
"600sel": "Mercedes 600 SEL",
"675lt": "McLaren 675 LT",
"765ltspider": "McLaren 765 LT Spider",
"918spyder": "Porsche 918 Spyder",
"2020ss": "Camaro 2020 SS",
"a9": "Audi A9",
"ae86": "Toyota AE86",
"aetron": "Audi E-Tron",
"ageraone": "Koenigsegg Agera One",
"amggt": "Mercedes AMG GT",
"amggt63s": "Mercedes AMG GT63S",
"amgvision": "Mercedes AMG VISION",
"atlantic": "Bugatti Atlantic",
"bacalar": "Bentley AC",
"bbentayga": "Bentley Bentayga",

// sport
"Comet2": "Comet2",
"Coquette": "Coquette",
"Ninef": "Ninef",
"Ninef2": "Ninef2",
"Jester": "Jester",
"Elegy2": "Elegy2",
"Infernus": "Infernus",
"Carbonizzare": "Carbonizzare",
"Dubsta2": "Dubsta2",
"Baller3": "Baller3",
"Huntley": "Huntley",
"Superd": "Superd",
"Windsor": "Windsor",
"BestiaGTS": "BestiaGTS",
"Banshee2": "Banshee2",
"EntityXF": "EntityXF",
"Neon": "Neon",
"Jester2": "Jester2",
"Turismor": "Turismor",
"Penetrator": "Penetrator",
"Omnis": "Omnis",
"Reaper": "Reaper",
"Italigtb2": "Italigtb2",
"Xa21": "Xa21",
"Osiris": "Osiris",
"Pfister811": "Pfister811",
"Zentorno": "Zentorno",
"bc": "Pagani Huayra",
"jesko2020": "Koenigsegg Jesko 2020",
"bmwi7": "BMW i7",
"evcs850": "Brabus 850",
"mbc63": "Mercedes AMG C63",
"opeladam": "Opel Adam",
"pursport": "Bugatti Supersport",
"sf90": "Ferrari Stradale SF90",
"16challenger": "Dodge Challenger",
"17m760i": "BMW 760i",
"18performante": "Lamborghini Performante",
"63g4x4": "Mercedes G63 4x4",
"190e": "Mercedes 190e",
"300sl": "Mercedes 300 SL",
"488pista": "Ferrari 488 Pista",
"600sel": "Mercedes 600 SEL",
"675lt": "McLaren 675 LT",
"765ltspider": "McLaren 765 LT Spider",
"918spyder": "Porsche 918 Spyder",
"2020ss": "Camaro 2020 SS",
"a9": "Audi A9",
"ae86": "Toyota AE86",
"aetron": "Audi E-Tron",
"ageraone": "Koenigsegg Agera One",
"amggt": "Mercedes AMG GT",
"amggt63s": "Mercedes AMG GT63S",
"amgvision": "Mercedes AMG VISION",
"atlantic": "Bugatti Atlantic",
"bacalar": "Bentley AC",
"bbentayga": "Bentley Bentayga",

// middle
"Apriora": "Lada Priora",
"bc": "Pagani Huayra",
"jesko2020": "Koenigsegg Jesko 2020",
"bmwi7": "BMW i7",
"evcs850": "Brabus 850",
"mbc63": "Mercedes AMG C63",
"opeladam": "Opel Adam",
"pursport": "Bugatti Supersport",
"sf90": "Ferrari Stradale SF90",
"16challenger": "Dodge Challenger",
"17m760i": "BMW 760i",
"18performante": "Lamborghini Performante",
"63g4x4": "Mercedes G63 4x4",
"190e": "Mercedes 190e",
"300sl": "Mercedes 300 SL",
"488pista": "Ferrari 488 Pista",
"600sel": "Mercedes 600 SEL",
"675lt": "McLaren 675 LT",
"765ltspider": "McLaren 765 LT Spider",
"918spyder": "Porsche 918 Spyder",
"2020ss": "Camaro 2020 SS",
"a9": "Audi A9",
"ae86": "Toyota AE86",
"aetron": "Audi E-Tron",
"ageraone": "Koenigsegg Agera One",
"amggt": "Mercedes AMG GT",
"amggt63s": "Mercedes AMG GT63S",
"amgvision": "Mercedes AMG VISION",
"atlantic": "Bugatti Atlantic",
"bacalar": "Bentley AC",
"bbentayga": "Bentley Bentayga",

// moto
"Faggio2": "Faggio2",
"Sanchez2": "Sanchez2",
"Enduro": "Enduro",
"PCJ": "PCJ",
"Hexer": "Hexer",
"Lectro": "Lectro",
"Nemesis": "Nemesis",
"Hakuchou": "Hakuchou",
"Ruffian": "Ruffian",
"Bmx": "Bmx",
"Scorcher": "Scorcher",
"BF400": "BF400",
"CarbonRS": "CarbonRS",
"Bati": "Bati",
"Double": "Double",
"Diablous": "Diablous",
"Cliffhanger": "Cliffhanger",
"Akuma": "Akuma",
"Thrust": "Thrust",
"Nightblade": "Nightblade",
"Vindicator": "Vindicator",
"Ratbike": "Ratbike",
"Blazer": "Blazer",
"Gargoyle": "Gargoyle",
"Sanctus": "Sanctus",

// aero room
"Buzzard2": "Buzzard2",
"Mammatus": "Mammatus",
"Luxor2": "Luxor2",
"bc": "Pagani Huayra",
"jesko2020": "Koenigsegg Jesko 2020",
"bmwi7": "BMW i7",
"evcs850": "Brabus 850",
"mbc63": "Mercedes AMG C63",
"opeladam": "Opel Adam",
"pursport": "Bugatti Supersport",
"sf90": "Ferrari Stradale SF90",
"16challenger": "Dodge Challenger",
"17m760i": "BMW 760i",
"18performante": "Lamborghini Performante",
"63g4x4": "Mercedes G63 4x4",
"190e": "Mercedes 190e",
"300sl": "Mercedes 300 SL",
"488pista": "Ferrari 488 Pista",
"600sel": "Mercedes 600 SEL",
"675lt": "McLaren 675 LT",
"765ltspider": "McLaren 765 LT Spider",
"918spyder": "Porsche 918 Spyder",
"2020ss": "Camaro 2020 SS",
"a9": "Audi A9",
"ae86": "Toyota AE86",
"aetron": "Audi E-Tron",
"ageraone": "Koenigsegg Agera One",
"amggt": "Mercedes AMG GT",
"amggt63s": "Mercedes AMG GT63S",
"amgvision": "Mercedes AMG VISION",
"atlantic": "Bugatti Atlantic",
"bacalar": "Bentley AC",
"bbentayga": "Bentley Bentayga",

// авто-донат
"deluxo": "Deluxo",
"bc": "Pagani Huayra",
"jesko2020": "Koenigsegg Jesko 2020",
"bmwi7": "BMW i7",
"evcs850": "Brabus 850",
"mbc63": "Mercedes AMG C63",
"opeladam": "Opel Adam",
"pursport": "Bugatti Supersport",
"sf90": "Ferrari Stradale SF90",
"16challenger": "Dodge Challenger",
"17m760i": "BMW 760i",
"18performante": "Lamborghini Performante",
"63g4x4": "Mercedes G63 4x4",
"190e": "Mercedes 190e",
"300sl": "Mercedes 300 SL",
"488pista": "Ferrari 488 Pista",
"600sel": "Mercedes 600 SEL",
"675lt": "McLaren 675 LT",
"765ltspider": "McLaren 765 LT Spider",
"918spyder": "Porsche 918 Spyder",
"2020ss": "Camaro 2020 SS",
"a9": "Audi A9",
"ae86": "Toyota AE86",
"aetron": "Audi E-Tron",
"ageraone": "Koenigsegg Agera One",
"amggt": "Mercedes AMG GT",
"amggt63s": "Mercedes AMG GT63S",
"amgvision": "Mercedes AMG VISION",
"atlantic": "Bugatti Atlantic",
"bacalar": "Bentley AC",
"bbentayga": "Bentley Bentayga",

}

/* */
exports.get = function (value) { return RealCarNames[value] }